---
galaxy_info:
  author: Herv√© Quatremain <rv4m@yahoo.co.uk>
  description: Create and configure a Quay Container Registry organization
  license: GPL-3.0-or-later
  min_ansible_version: "2.1"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      version:
        - all
    - name: MacOSX
      versions:
        - all
    - name: Windows
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - quay
    - registry
dependencies: []
