---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: trailing-whitespace
        exclude: ^docs/
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        types:
          - yaml
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.2.1
    hooks:
      - id: ansible-lint
        types:
          - yaml
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        language_version: python3.10
        entry: black
        args: [--line-length, "94"]
        types:
          - python
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        types:
          - python
...
