---
- name: Ensure the repositories exist
  herve4m.quay.quay_repository:
    name: "{{ quay_org_name }}/{{ item['name'] }}"
    visibility: "{{ item['visibility'] | default(omit) }}"
    description: "{{ item['description'] | default(omit) }}"
    perms: "{{ item['perms'] | default(omit) }}"
    repo_state: "{{ item['repo_state'] | default(omit) }}"
    append: true
    state: present
    quay_token: "{{ quay_org_token | default(omit) }}"
    quay_username: "{{ quay_org_username | default(omit) }}"
    quay_password: "{{ quay_org_password | default(omit) }}"
    quay_host: "{{ quay_org_host | default(omit) }}"
    validate_certs: "{{ quay_org_validate_certs | default(omit) }}"
  loop: "{{ quay_org_repositories }}"
