---
- name: Ensure the teams exist
  herve4m.quay.quay_team:
    organization: "{{ quay_org_name }}"
    name: "{{ item['name'] }}"
    description: "{{ item['description'] | default(omit) }}"
    role: "{{ item['role'] | default(omit) }}"
    members: "{{ item['members'] | default(omit) }}"
    append: false
    state: present
    quay_token: "{{ quay_org_token | default(omit) }}"
    quay_username: "{{ quay_org_username | default(omit) }}"
    quay_password: "{{ quay_org_password | default(omit) }}"
    quay_host: "{{ quay_org_host | default(omit) }}"
    validate_certs: "{{ quay_org_validate_certs | default(omit) }}"
  loop: "{{ quay_org_teams }}"
